   export const blogPosts = [
     {
       id: "1",
       title: "Modern Home Design Trends for 2025",
       excerpt: "Explore the latest trends in modern home design that are shaping the future of residential architecture.",
       content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
       date: "May 10, 2025",
       author: "John Doe",
       category: "Design Trends",
       image: "../assets/Gallery/proj1/p1.jpg",
     },
     {
       id: "2",
       title: "The Importance of Vaasthu in Home Design",
       excerpt: "Learn how traditional Vaasthu principles can be incorporated into modern home design for better energy flow.",
       content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
       date: "April 28, 2025",
       author: "Jane Smith",
       category: "Vaasthu",
       image: "../assets/Gallery/blogs/Vastu Chart-Photoroom.png",
     },
     {
       id: "3",
       title: "Sustainable Building Materials for Eco-Friendly Homes",
       excerpt: "Discover sustainable building materials that reduce environmental impact without compromising on quality or aesthetics.",
       content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
       date: "April 15, 2025",
       author: "Michael Johnson",
       category: "Sustainability",
       image: "../assets/Gallery/blogs/sustainable-home-tech.jpg",
     },
     {
       id: "4",
       title: "How to Choose the Right Architect for Your Project",
       excerpt: "Tips for selecting the perfect architect who understands your vision and can bring it to life.",
       content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
       date: "April 5, 2025",
       author: "Sarah Williams",
       category: "Planning",
       image: "../assets/Gallery/blogs/architect.jpeg",
     },
     {
       id: "5",
       title: "Interior Design Tips for Small Spaces",
       excerpt: "Creative solutions to maximize functionality and style in compact living areas.",
       content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
       date: "March 22, 2025",
       author: "David Brown",
       category: "Interior Design",
       image: "../assets/Gallery/proj1/4.jpg",
     },
     {
       id: "6",
       title: "The Building Process: What to Expect",
       excerpt: "A comprehensive guide to the construction process from planning to completion.",
       content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
       date: "March 10, 2025",
       author: "Emily Davis",
       category: "Construction",
       image: "../assets/Gallery/proj8/18.jpg",
     },
   ];
