   export const blogPosts = [
     {
       id: "1",
       title: "Modern Home Design Trends for 2025",
       excerpt: "Explore the latest trends in modern home design that are shaping the future of residential architecture.",
       content: "Modern home design in 2025 is all about blending functionality with sustainability and style. This year’s trends focus on minimalist aesthetics, smart home integration, and eco-friendly materials. Natural textures, earthy tones, and biophilic design elements are bringing the outdoors in, while multifunctional spaces and modular furniture support flexible lifestyles. Technology continues to play a key role, with voice-controlled systems, energy-efficient lighting, and AI-powered appliances becoming standard. Whether you're building new or updating your space, 2025 is the year to embrace comfort, innovation, and conscious living in home design.",
       date: "May 10, 2025",
       author: "Rajesh R",
       category: "Design Trends",
       image: "../assets/Gallery/proj1/p1.jpg",
     },
     {
       id: "2",
       title: "The Importance of Vaasthu in Home Design",
       excerpt: "Learn how traditional Vaasthu principles can be incorporated into modern home design for better energy flow.",
       content: "Vaasthu Shastra, the ancient Indian science of architecture, plays a vital role in creating harmony between a home and the natural elements. By aligning the layout, structure, and energy flow of a house with cosmic principles, Vaasthu enhances peace, prosperity, and well-being for its occupants. Incorporating Vaasthu in home design helps optimize natural light, ventilation, and spatial energy, leading to a balanced and positive living environment. Whether building a new home or renovating an existing one, Vaasthu offers timeless guidelines to ensure your space nurtures both physical comfort and spiritual harmony.",
       date: "April 28, 2025",
       author: "Jaison V",
       category: "Vaasthu",
       image: "../assets/Gallery/blogs/Vastu Chart-Photoroom.png",
     },
     {
       id: "3",
       title: "Sustainable Building Materials for Eco-Friendly Homes",
       excerpt: "Discover sustainable building materials that reduce environmental impact without compromising on quality or aesthetics.",
       content: "Sustainable building materials are at the heart of eco-friendly home construction, promoting a greener and more responsible approach to design. From recycled steel and reclaimed wood to bamboo, rammed earth, and low-VOC paints, these materials reduce environmental impact without compromising durability or style. They help conserve natural resources, improve indoor air quality, and enhance energy efficiency. Choosing sustainable materials not only supports a healthier planet but also creates homes that are long-lasting, cost-effective, and aligned with modern eco-conscious values.",
       date: "April 15, 2025",
       author: "Michael Johnson",
       category: "Sustainability",
       image: "../assets/Gallery/blogs/sustainable-home-tech.jpg",
     },
     {
       id: "4",
       title: "How to Choose the Right Architect for Your Project",
       excerpt: "Tips for selecting the perfect architect who understands your vision and can bring it to life.",
       content: "Choosing the right architect is a critical step in turning your vision into reality. A skilled architect not only brings creativity and technical expertise but also ensures your project stays within budget and complies with regulations. Start by reviewing their portfolio to see if their style aligns with your goals, and check credentials, licenses, and client reviews. Communication is key—select someone who listens, understands your needs, and can clearly explain ideas. Whether it's a home, office, or commercial space, the right architect will guide you from concept to completion with confidence and clarity.",
       date: "April 5, 2025",
       author: "Sarah John",
       category: "Planning",
       image: "../assets/Gallery/blogs/architect.jpeg",
     },
     {
       id: "5",
       title: "Interior Design Tips for Small Spaces",
       excerpt: "Creative solutions to maximize functionality and style in compact living areas.",
       content: "Designing small spaces requires smart strategies to make every square foot count. With the right interior design tips, even the tiniest rooms can feel open, functional, and stylish. Start by using light colors and mirrors to enhance the sense of space. Choose multi-functional furniture like storage beds or foldable tables, and keep the layout clutter-free. Vertical storage, wall-mounted shelves, and built-in units can maximize storage without taking up floor space. Thoughtful lighting and minimalistic décor help create a cozy yet breathable environment—proving that great design isn’t about size, but smart use of space.",
       date: "March 22, 2025",
       author: "Vimal Mohan",
       category: "Interior Design",
       image: "../assets/Gallery/proj1/4.jpg",
     },
     {
       id: "6",
       title: "The Building Process: What to Expect",
       excerpt: "A comprehensive guide to the construction process from planning to completion.",
       content: "The building process is an exciting journey that transforms your ideas into a finished structure. Understanding what to expect can make the experience smoother and less stressful. It typically begins with planning and design, followed by securing permits and finalizing budgets. Next comes site preparation, foundation work, structural framing, and the installation of essential systems like plumbing and electrical. As the project progresses, finishing touches like flooring, painting, and fixtures bring your space to life. Throughout the process, communication with your builder or architect is key to staying on track, managing changes, and ensuring your dream home or space becomes a reality.",
       date: "March 10, 2025",
       author: "Vinod Mohan",
       category: "Construction",
       image: "../assets/Gallery/proj8/18.jpg",
     },
   ];
